### PR TITLE
Uses EventSource instead of websockets

### PR DESCRIPTION
**Pull request by amir20**

### CODE REVIEW

**Comment by amir20** [comment]
@kmlucy I did some research and it seems like `Sever Events` is superior compared to `WebSockets`. I started playing with it and it does seem simpler. I also tested it behind a proxy and SSL is no longer issue. So I am going to merge this and up the minor version since it is a new feature. I am removing the `--ssl` flag in favor of just not needing a flag at all since `EventSource` is just over HTTP/s.

**Comment by amir20** [comment]
Related to #6

**Comment by amir20** [comment]
Also forgot to mention that auto reconnect with eventsource seems to be built out of the box for most browsers. 👍

**Comment by kmlucy** [comment]
I just tested the latest version, and it seems to work fine. I removed the --ssl flag and removed the portions of my proxy location block relevant to websockets. 

With the new version, the logs do not auto-update reliably, however. They seem to only update every few minutes. Is that a bug, or will continuous updating not work with server events?

**Comment by amir20** [comment]
> With the new version, the logs do not auto-update reliably, however. 

No that must be a bug. I was able to test it and it does work for me. I did a HTTP load test with `siege` and saw the logs fly by. 

Is there a way you can help me debug? I haven't checked the refresh when on a proxy. I can check that next. 

Let me know if you find anything.

**Pull request merged**
