### PR TITLE
Trims top events depending on scroll status

### PR DESCRIPTION
**Pull request by amir20**

### CODE REVIEW

**Comment by amir20** [comment]
@flarco Be so kind and try this PR out. It's tagged at `amir20/dozzle:pr-1860`. 

The work I did is very minimal. I changed the logic to trim and pause when scrolled up. If you open console, you should see the number of logs skipped when scroll up. The UI work still needs to be done to show that. 

Thanks!

**Comment by flarco** [comment]
@amir20 got to trying it out. I'm seeing the skipped lines 👍 
I'll start using it across my environments and let you know if I see any issues
image

**Comment by amir20** [comment]
Sounds good. As long as your browser doesn't run out of memory I think this solution works. The rest is just UI work.

**Comment by amir20** [comment]
Coming back to this @flarco. Everything work out ok? I have been working on some refactoring but hope to come back to this.

**Comment by flarco** [comment]
@amir20 yes, everything has been working just fine 👍

**Comment by amir20** [comment]
This is now merged in master. My CSS is rusty so I didn't do the zig zag line yet. Going to test it a little.

**Pull request merged**
