### PR TITLE
Cleans up search by removing for loop

### PR DESCRIPTION
**Pull request by amir20**

### CODE REVIEW

**Comment by amir20** [comment]
@Coteh adding you to this PR since I was changing your code. I removed the for loop that integrated over all logs as it was causing performance problems. 

I also did some clean up and using hash in the url to trigger the color. I hope in the future to make it work through page navigations too.

**Comment by Coteh** [comment]
I was just about to write a comment when you merged the branch. Very nice solution! Wish I had done it that way from the start.

One thing I noticed after starting it just now using logs from work is that the log lines don't seem to wrap anymore if they're too long. You can easily see this using the split pane view. Once I'm done work I'll try to take some screenshots on my personal machine using dummy logs, if you like.

**Comment by amir20** [comment]
> One thing I noticed after starting it just now using logs from work is that the log lines don't seem to wrap anymore if they're too long. You can easily see this using the split pane view. Once I'm done work I'll try to take some screenshots on my personal machine using dummy logs, if you like.

That's a bug. I just added a new setting to not wrap. But looks like it defaults to not wrapping.

**Comment by amir20** [comment]
Should be fixed now in 436e93c.

**Pull request merged**
