### PR TITLE
feat: supports auth ttl to override session with DOZZLE_AUTH_TTL env.

### PR DESCRIPTION
**Pull request by amir20**
Fixes https://github.com/amir20/dozzle/issues/3309

### CODE REVIEW

**Comment by FibreTTP** [comment]
This works well, but since there is no expiry claim set in the JWT, the Expiry of the cookie can be set to whatever and Dozzle will accept it (I've tested this). JWTs without an expiry claim never expire.

For my local-only usecase this is acceptable, but definitely not _good_.

I'm also not sure what the `timestamp` claim you're setting is doing. It seems the standard is to use `iat` (Issued At).

**Comment by amir20** [comment]
That's a good point. I currently don't do anything with JWT expiration. But to do this right I probably should.

**Comment by amir20** [comment]
JWT now properly expires. Can you test out again? Turns out I wasn't using expiration correctly.

**Comment by FibreTTP** [comment]
Looks good and works :)

**Pull request merged**
