### PR TITLE
Fix removed newline from password file

### PR DESCRIPTION
**Pull request by dima-bzz**

### CODE REVIEW

**Comment by dima-bzz** [comment]
@amir20 Well, then we will assign the correctness of the user name to the user. This is about spaces.

**Comment by amir20** [comment]
I don't understand. TrimRight should be used for all values. Is there an example where this would not work?

**Comment by dima-bzz** [comment]
In my opinion, spaces and newline at the beginning and end of the line should be removed in the user name. And only newline should be deleted in the password

**Comment by amir20** [comment]
I don't think I have ever seen a system that cared for spaces in the beginning.  So no reason to over think it. As of right now, I only strip `\r\n` anyway.  Dozzle is a small tool with just me maintaining. I want to keep it simple with less code so it is easier to find bugs. 

Also since Dozzle is a developer tool, hopefully engineers know what they are doing :)

**Comment by dima-bzz** [comment]
Okay, I agree with you. But I would replace trimRight with Trim. I think we can end here.

**Comment by amir20** [comment]
ok. i'll do that.

**Pull request closed without merging**
