### PR TITLE
Adds a simple healthcheck every 2s

### PR DESCRIPTION
**Pull request by amir20**

### CODE REVIEW

**Comment by amir20** [comment]
Fixes #1810

**Comment by MetalArend** [comment]
LGTM, only maybe missing some documentation :speak_no_evil:

**Comment by amir20** [comment]
Merged for now. Let's have it in master for a while before adding documentation.

**Comment by amir20** [comment]
@MetalArend See #1819. Sounds like there is a spike on CPU. I guess now it makes sense to just disable healthcheck.

**Comment by MetalArend** [comment]
Shame. I was already looking into how to enable the healthcheck from only the `--health-cmd` flags on docker run, and ran into this: https://github.com/moby/moby/issues/43843

**Comment by MetalArend** [comment]
Basically, it seems impossible to add the same healthcheck as you would do in the Dockerfile with only the docker run flags. I have been trying to set the SHELL in the Dockerfile, have been checking the ENTRYPOINT, but with no luck. I'm hoping anyone from moby itself might have the answer on how to do this, or how to fix it.

**Comment by amir20** [comment]
Well that really sucks. Maybe a short term solution would be to keep the `healthcheck` command, but only enable it with an `ENV` variable. If the variable is off, then it would be a no op. I would have to see if that would still cause a CPU spike. 

On the bug you created, how does using `docker-compose` work? Does it produce the same bug?

**Comment by amir20** [comment]
@MetalArend I think using docker compose works. See solution below...

```
version: "3"
services:
  dozzle:
    container_name: dozzle
    image: amir20/dozzle:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 8080:8080
    environment:
      DOZZLE_LEVEL: trace
    healthcheck:
      test: [ "CMD", "/dozzle", "healthcheck" ]
      interval: 3s
      timeout: 30s
      retries: 5
      start_period: 30s
```

I am able to see `dozzle  | level=trace msg="Executing healthcheck request"`.

So I think this works.

**Comment by MetalArend** [comment]
Yeah, indeed, docker-compose has no issues. But it would be a shame to have to create a yaml file only to run one container :) I would be okay with having to write some strange json to pass it to the health-cmd flag, but it will not accept json :(

Let's see if maybe there is a known work-around. At least one can ask nicely, and hope there is a solution.

**Comment by corhere** [comment]
While you can't (currently) configure a shell-less health check test from the docker CLI, you can use the `--no-healthcheck` flag to disable any check set in the Dockerfile.

I would advise against setting a short health-check interval as each check is rather expensive: https://github.com/moby/moby/issues/33933

**Comment by amir20** [comment]
> I would advise against setting a short health-check interval as each check is rather expensive

Yea I learned that. :) 

The problem with healthcheck is that the initial check will be 0s then 30s. 0s will fail because container is still starting up. 30s later the container will be green status. I wish there was a way to say don't check for another 3s. 

So my (crappy) compromise was to make it check often to unblock use cases where one needs to wait for Dozzle to be green.

**Comment by corhere** [comment]
> The problem with healthcheck is that the initial check will be 0s then 30s. 0s will fail because container is still starting up. 30s later the container will be green status. I wish there was a way to say don't check for another 3s.

We're working on it! https://github.com/moby/moby/pull/40894

**Pull request merged**
