### PR TITLE
Skips only the push int tests

### PR DESCRIPTION
**Pull request by amir20**

### CODE REVIEW

**Comment by amir20** [comment]
@dima-bzz FYI on this. Moving if skip to the push step. 

Thanks again for finding this solution.

**Comment by dima-bzz** [comment]
@amir20 I was glad to help)

**Comment by dima-bzz** [comment]
@amir20 I'm not sure if integration test is needed because it fails with an error.

image

**Comment by amir20** [comment]
Ah I need to skip that step too.

**Comment by amir20** [comment]
The problem is docker user/pass do not exist

**Comment by amir20** [comment]
See 199c517

**Comment by dima-bzz** [comment]
@amir20 Everything is fine now

image

**Pull request merged**
