### PR TITLE
fix: actions on log UI issues

### PR DESCRIPTION
**Pull request by akash-ramaswamy**
#2579

### CODE REVIEW

**Comment by amir20** [comment]
Won't have time to test this until later. But perhaps you can also include the fixes to search more in one PR?

**Comment by akash-ramaswamy** [comment]
> Won't have time to test this until later. But perhaps you can also include the fixes to search more in one PR?

this solves that issue too, which you mentioned in this https://github.com/amir20/dozzle/pull/2572#issuecomment-1848424830

**Comment by amir20** [comment]
How does this fix the search? That's an icon on the left that I am saying should be moved to the right with the other icons. Can you send a screenshot?

**Comment by akash-ramaswamy** [comment]
> How does this fix the search? That's an icon on the left that I am saying should be moved to the right with the other icons. Can you send a screenshot?

Oh sorry that you misunderstood! I was saying that the copy button will not be facing issues anymore, since i added `word-break` property.

**Comment by akash-ramaswamy** [comment]
This is after the fix applied for JSON bug

image

**Comment by amir20** [comment]
Right. As part of this fix can you also moved the jump to context button to the right so it's consistent?

**Comment by amir20** [comment]
It does look like the JSON bug is fixed now. 🎉

**Comment by akash-ramaswamy** [comment]
> Right. As part of this fix can you also moved the jump to context button to the right so it's consistent? That was one of the original requirements. 😁

I think moving this would require little more work in UI too, As i want to make the button same as copy-button style :) ? could the release be kept hold until then?

**Comment by akash-ramaswamy** [comment]
> Right. As part of this fix can you also moved the jump to context button to the right so it's consistent? That was one of the original requirements. 😁

Also I thought that this could be a separate issue, or linked to #2571 ?

**Comment by amir20** [comment]
I can merge this soon but I think I'll hold off to release. Search feature is used a lot so it's probably best to be consistent before releasing.

**Pull request merged**
