### PR TITLE
Improve i18n support

### LINKED ISSUE #2417: Support for More Specific Locale Codes (e.g., en-US, zh-TW)
**Is your feature request related to a problem? Please describe.**
The current locale support only includes two-letter language codes like `en` and `zh`. This doesn't account for more specific locale codes such as `en-US`, `zh-CN`, or `zh-TW`.

**Describe the solution you'd like**
I would like the project to extend its locale support to include more specific locale codes. This would make the application more versatile and better suited for international audiences.

**Additional context**
I am looking forward to this feature being implemented and would be happy to provide a `zh-TW` translation to supplement the existing `zh` (which is actually `zh-CN`).

### PR DESCRIPTION
**Pull request by PeterDaveHello**
Just a small improvement, close #2417

### CODE REVIEW

**Comment by amir20** [comment]
Hey @PeterDaveHello so I was testing this. It seems like the below would just work. Vue-i18n would try `en-US` then `en` then fallback to `fallbackLocale`. 

```diff
--- a/assets/modules/i18n.ts
+++ b/assets/modules/i18n.ts
@@ -9,7 +9,7 @@ const messages = Object.fromEntries(
 );
 const i18n = createI18n({
   legacy: false,
-  locale: navigator.language.slice(0, 2),
+  locale: navigator.language,
   fallbackLocale: "en",
   messages,
 });
```

Does that work for you too? Which then I think it would be a lot easier.

**Comment by amir20** [comment]
My solution prints a lot of warnings. So I think this solution works.

**Comment by amir20** [comment]
@PeterDaveHello going to merge this. I assume you will send another PR with specific country locales?

**Comment by PeterDaveHello** [comment]
> @PeterDaveHello going to merge this. I assume you will send another PR with specific country locales? 

Sure

**Comment by PeterDaveHello** [comment]
@amir20 sent here: #2425

**Comment by amir20** [comment]
> BTW, this change doesn't seem to be reflected on https://github.com/amir20/dozzle/releases/tag/v5.0.6 changelog?

Your commit didn't have semantic git messages so it didn't get included.

**Pull request merged**
