### PR TITLE
fix: moves the favorite star button the left

### PR DESCRIPTION
**Pull request by amir20**
Screenshot 2023-11-25 at 6 59 39 PM

### CODE REVIEW

**Comment by uhlhosting** [comment]
Hi, I have tried several ways to enter the docker image, and apply the patch manually, that did not worked for me:

```
root@pac:/home/pac# docker exec -it df676f508ef7 /bin/sh
OCI runtime exec failed: exec failed: unable to start container process: exec: "/bin/sh": stat /bin/sh: no such file or directory: unknown
root@pac:/home/pac# sudo docker exec -it df676f508ef7 "lsb_release -a"
OCI runtime exec failed: exec failed: unable to start container process: exec: "lsb_release -a": executable file not found in $PATH: unknown
root@pac:/home/pac# sudo docker exec -it df676f508ef7 "uname -a"
OCI runtime exec failed: exec failed: unable to start container process: exec: "uname -a": executable file not found in $PATH: unknown
root@pac:/home/pac# sudo docker exec -it df676f508ef7 "uptime"
```

upon discussion with a colleague and checking the code, we noticed you use `FROM scratch` inside docker file at [line 51](https://github.com/amir20/dozzle/blob/master/Dockerfile#L51) actually just replacing it with `FROM alpine` should work in theory.

**Comment by amir20** [comment]
> Hi, I have tried several ways to enter the docker image, and apply the patch manually, that did not worked for me:

What? Why do you need to do that? Just use `amir20:dozzle/pr-2535` as I said in https://github.com/amir20/dozzle/issues/2522#issuecomment-1826423213.

**Comment by uhlhosting** [comment]
@amir20 all works as designed, thanks for the quick fix!

**Comment by amir20** [comment]
I am still not too happy with it, so I'll come back to it later. I think this fix breaks other things.

**Comment by uhlhosting** [comment]
@amir20 I haven't seen anything broken yet.

**Pull request closed without merging**
